version: "2"

services:

  phpmyfaq:
    build: .
    links:
    - mariadb
    - elasticsearch
    ports:
    - "8080:80"
    volumes:
    - ./volumes/phpmyfaq-attachments:/var/www/html/phpmyfaq/attachments
    - ./volumes/phpmyfaq-data:/var/www/html/phpmyfaq/data
    - ./volumes/phpmyfaq-images:/var/www/html/phpmyfaq/images
    - ./config:/var/www/html/phpmyfaq/config

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - mariadb:db
    ports:
    - "8001:80"
    volumes:
    - ./volumes/phpmyadmin-sessions:/sessions
    environment:
    - MYSQL_ROOT_PASSWORD=iop

  mariadb:
    image: mariadb:10.2.9
    environment:
    - MYSQL_ROOT_PASSWORD=iop
    - MYSQL_DATABASE=phpmyfaq
    - MYSQL_USER=phpmyfaq
    - MYSQL_PASSWORD=phpmyfaq
    volumes:
    - ./volumes/mariadb-data:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:5.5.2
    volumes:
    - ./volumes/elasticsearch-data:/usr/share/elasticsearch/data
